### ISSUE TITLE
CURRENT ROADMAP

### ISSUE THREAD

**Issue by tjakubo2** [tjakubo2/TTS_xwing#37]
Main features (order matters):  
- [x] Move zone objects checks to Physics.cast
- [x] Better handling for 6+ ships assignment  
- [ ] Move token handling to Physics.cast checks  
- [ ] UI: Indicators for tokens assigned to ship (toggleable)
- [ ] Hotkeys system  
- [ ] UI: PS order in sidenote (toggleable)  
- [ ] UI: Planning phase state (toggleable)
(more later)

Side features & requests (order doesn't matter):
- [ ] Kallus token  
- [x] Deleted dials handling
- [ ] Bomb range ruler overhaul
- [ ] Ship deploy token similiar to bomb drop

Feel free to request features here.

**Comment by tjakubo2** [comment]
I didn't forget requests from previous threads, but for now ship to ship range check would have a dependence on hotkey system (unless someone has a sane idea on how to trigger range check between two ships) and template <-> obstacle overlap detection looks a bit tricky.

**Comment by JohnnyCheese** [comment]
Would it be possible to include support for epic games? Huge ships movement automation and larger play area?

**Comment by tjakubo2** [comment]
@JohnnyCheese 
So, it is possible, BUT. Aside from epic being lil bit back on a priority list (few people playing, long games), I'd need one important thing to even start out with it: how their moves precisely work.

Take a look here: https://gfycat.com/LimitedGloomyCats
We need to know how their moves look step-by-step, or more like a trajectory like on this video. 
Possibly someone would have to help to get them in if we want them sooner that everything from Standard Play.

As for the one big playmat, it's much more feasible even without Epic. Definitely on the list to do on the way (as a part of table layout changing to be done).

**Comment by tjakubo2** [comment]
Single deleted dials are now restored with a notification (side features list).

**Comment by tjakubo2** [comment]
Because TTS updates real fast and we get A LOT of changes and additions for scripting, I'm pretty much forced to improvise as we go, trying to follow plans quickly renders future points obsolete (with features we keep getting).
Sorry, if anyone is interested in what is currently under the hammer and can be expected sooner than later, hit me up on Discord as that's quite fluid :)
