### ISSUE TITLE
To-do ATM

### ISSUE THREAD

**Issue by tjakubo2** [tjakubo2/TTS_xwing#9]
- [x] - Dials for Fang Fighter
- [x] -- Update spawner with these
- [x] - Make main table indifferent to http/https in the links
- [ ] - Update spawner picture guide with Fab's generator
- [x] - Clean up and include spawner in repo
- [x] - Include Rigged Cargo Chute debris in the main table
- [ ] - Make some sort of arc indicator and include it
